{
    "openapi": "3.0.0",
    "servers": [
        {
            "url": "https://sourcerepo.googleapis.com/"
        }
    ],
    "x-hasEquivalentPaths": true,
    "info": {
        "contact": {
            "name": "Google",
            "url": "https://google.com"
        },
        "description": "Accesses source code repositories hosted by Google.",
        "title": "Cloud Source Repositories",
        "version": "v1",
        "x-apiClientRegistration": {
            "url": "https://console.developers.google.com"
        },
        "x-apisguru-categories": [
            "developer_tools"
        ],
        "x-logo": {
            "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
        },
        "x-origin": [
            {
                "converter": {
                    "url": "https://github.com/lucybot/api-spec-converter",
                    "version": "2.7.31"
                },
                "format": "google",
                "url": "https://sourcerepo.googleapis.com/$discovery/rest?version=v1",
                "version": "v1"
            }
        ],
        "x-preferred": true,
        "x-providerName": "googleapis.com",
        "x-serviceName": "sourcerepo"
    },
    "tags": [
        {
            "name": "projects"
        }
    ],
    "paths": {
        "/v1/{name}": {
            "delete": {
                "description": "Deletes a repo.",
                "operationId": "sourcerepo.projects.repos.delete",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/cloud-platform"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.full_control"
                        ]
                    }
                ],
                "tags": [
                    "projects"
                ]
            },
            "get": {
                "description": "Returns information about a repo.",
                "operationId": "sourcerepo.projects.repos.get",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/cloud-platform"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.full_control"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.read_only"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.read_write"
                        ]
                    }
                ],
                "tags": [
                    "projects"
                ]
            },
            "patch": {
                "description": "Updates information about a repo.",
                "operationId": "sourcerepo.projects.repos.patch",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/cloud-platform"
                        ]
                    }
                ],
                "tags": [
                    "projects"
                ]
            }
        },
        "/v1/{name}/config": {
            "get": {
                "description": "Returns the Cloud Source Repositories configuration of the project.",
                "operationId": "sourcerepo.projects.getConfig",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/cloud-platform"
                        ]
                    }
                ],
                "tags": [
                    "projects"
                ]
            },
            "patch": {
                "description": "Updates the Cloud Source Repositories configuration of the project.",
                "operationId": "sourcerepo.projects.updateConfig",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/cloud-platform"
                        ]
                    }
                ],
                "tags": [
                    "projects"
                ]
            }
        },
        "/v1/{name}/repos": {
            "get": {
                "description": "Returns all repos belonging to a project. The sizes of the repos are\nnot set by ListRepos.  To get the size of a repo, use GetRepo.",
                "operationId": "sourcerepo.projects.repos.list",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/cloud-platform"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.full_control"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.read_only"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.read_write"
                        ]
                    }
                ],
                "tags": [
                    "projects"
                ]
            }
        },
        "/v1/{parent}/repos": {
            "post": {
                "description": "Creates a repo in the given project with the given name.\n\nIf the named repository already exists, `CreateRepo` returns\n`ALREADY_EXISTS`.",
                "operationId": "sourcerepo.projects.repos.create",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/cloud-platform"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.full_control"
                        ]
                    }
                ],
                "tags": [
                    "projects"
                ]
            }
        },
        "/v1/{resource}:getIamPolicy": {
            "get": {
                "description": "Gets the access control policy for a resource.\nReturns an empty policy if the resource exists and does not have a policy\nset.",
                "operationId": "sourcerepo.projects.repos.getIamPolicy",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/cloud-platform"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.full_control"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.read_only"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.read_write"
                        ]
                    }
                ],
                "tags": [
                    "projects"
                ]
            }
        },
        "/v1/{resource}:setIamPolicy": {
            "post": {
                "description": "Sets the access control policy on the specified resource. Replaces any\nexisting policy.",
                "operationId": "sourcerepo.projects.repos.setIamPolicy",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/cloud-platform"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.full_control"
                        ]
                    }
                ],
                "tags": [
                    "projects"
                ]
            }
        },
        "/v1/{resource}:testIamPermissions": {
            "post": {
                "description": "Returns permissions that a caller has on the specified resource.\nIf the resource does not exist, this will return an empty set of\npermissions, not a NOT_FOUND error.",
                "operationId": "sourcerepo.projects.repos.testIamPermissions",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/cloud-platform"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.full_control"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.read_only"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/source.read_write"
                        ]
                    }
                ],
                "tags": [
                    "projects"
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "Oauth2": {
                "description": "Oauth 2.0 authentication",
                "type": "oauth2",
                "flows": {
                    "implicit": {
                        "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
                        "scopes": {
                            "https://www.googleapis.com/auth/cloud-platform": "View and manage your data across Google Cloud Platform services",
                            "https://www.googleapis.com/auth/source.full_control": "Manage your source code repositories",
                            "https://www.googleapis.com/auth/source.read_only": "View the contents of your source code repositories",
                            "https://www.googleapis.com/auth/source.read_write": "Manage the contents of your source code repositories"
                        }
                    }
                }
            }
        }
    }
}